### ISSUE TITLE
Multiple Lines in Event Description

### ISSUE THREAD

**Issue by DeltaKiloz** [psmitty7373/mcscop#14]
For the bottom column "Event Description" in the bottom events section, would like the ability to enter multiple lines instead of just one line when you go back to modify it. Either something like "Alt+Enter" or "Ctrl+Enter" for new line return would be great, or just have "Enter" be new line return instead of terminating the field entry. 

It allows multiple lines during the initial entry, but not when you go back to modify the event.

**Comment by psmitty7373** [comment]
Shift-enter does newlines... unfortunately because of cell-editing its tricky to know if you are done, or want a new line... does the shift-enter meet the need?

**Comment by DeltaKiloz** [comment]
That does work! Thought I had tried it before. Good to go.
